[workspace]

resolver = '2'

members = [
    'chess-bitboard',
    'chess-lookup',
    'chess-lookup-generator',
    'chess-movegen',
    'chess-cli',
]

[workspace.dependencies.chess]
version = '3'

[profile.release]
debug = true
